// src/Screenshots/operations/Scan/index.tsx
import React, { ReactElement, useCallback } from 'react';
import QrScanner from 'qr-scanner';
import useStore from '../../hooks/useStore';
import useCall from '../../hooks/useCall';
import useCanvasContextRef from '../../hooks/useCanvasContextRef';
import useHistory from '../../hooks/useHistory';
import useReset from '../../hooks/useReset';
import ScreenshotsButton from '../../ScreenshotsButton';
import composeImage from '../../composeImage';

export default function Scan(): ReactElement {
  const { image, width, height, history, bounds, lang } = useStore();
  const canvasContextRef = useCanvasContextRef();
  const [, historyDispatcher] = useHistory();
  const call = useCall();
  const reset = useReset();

  const onClick = useCallback(() => {
    historyDispatcher.clearSelect();
    setTimeout(() => {
      if (!canvasContextRef.current || !image || !bounds) {
        return;
      }
      composeImage({
        image,
        width,
        height,
        history,
        bounds,
      }).then(async (blob) => {
        try {
          const result = await QrScanner.scanImage(blob);
          if (result) {
            call('onScan', result);
          }
        } catch (error) {
          console.error('Error:', error);
        }

        reset();
      });
    });
  }, [canvasContextRef, historyDispatcher, image, width, height, history, bounds, call, reset]);

  return <ScreenshotsButton title={lang.operation_scan_title} icon="icon-scan" onClick={onClick} />;
}

// src/screenshot/operations/scan/index.vue
<script setup lang="ts">
import QrScanner from 'qr-scanner'
import { useCall } from '../../hooks/use-call'
import { useHistory } from '../../hooks/use-history'
import { useReset } from '../../hooks/use-reset'
import { composeImage } from '../../utils/image'
import { useStore } from '../../store'
import ScreenshotButton from '../../screenshot-button/index.vue'

const store = useStore()
const [, historyDispatcher] = useHistory()
const call = useCall()
const reset = useReset()

const onClick = () => {
  const { image, width, height, history, bounds } = store
  historyDispatcher.clearSelect()
  setTimeout(() => {
    if (!store.canvasContext || !image || !bounds) {
      return
    }
    composeImage({
      image,
      width,
      height,
      history,
      bounds,
    }).then(async (blob) => {
      try {
        const result = await QrScanner.scanImage(blob)
        if (result) {
          // call('onScan', result) - 扫码
        }
      } catch (error) {
        console.error('Error:', error)
      }

      reset()
    })
  })
}
</script>

<template>
  <ScreenshotButton title="扫码" icon="icon-scan" @click="onClick" />
</template>
