// src/Screenshots/operations/Ok/index.tsx
import React, { ReactElement, useCallback } from 'react'
import useStore from '../../hooks/useStore'
import useCall from '../../hooks/useCall'
import useCanvasContextRef from '../../hooks/useCanvasContextRef'
import useHistory from '../../hooks/useHistory'
import useReset from '../../hooks/useReset'
import ScreenshotsButton from '../../ScreenshotsButton'
import composeImage from '../../composeImage'

export default function Ok(): ReactElement {
  const { image, width, height, history, bounds, lang } = useStore()
  const canvasContextRef = useCanvasContextRef()
  const [, historyDispatcher] = useHistory()
  const call = useCall()
  const reset = useReset()

  const onClick = useCallback(() => {
    historyDispatcher.clearSelect()
    setTimeout(() => {
      if (!canvasContextRef.current || !image || !bounds) {
        return
      }
      composeImage({
        image,
        width,
        height,
        history,
        bounds
      }).then(blob => {
        call('onOk', blob, bounds)
        reset()
      })
    })
  }, [canvasContextRef, historyDispatcher, image, width, height, history, bounds, call, reset])

  return <ScreenshotsButton title={lang.operation_ok_title} icon='icon-ok' onClick={onClick} />
}

// src/screenshot/operations/ok/index.vue
<script setup lang="ts">
import { useHistory } from '../../hooks/use-history'
import { useReset } from '../../hooks/use-reset'
import { composeImage } from '../../utils/image'
import { useStore } from '../../store'
import { useCall } from '../../hooks/use-call'
import ScreenshotButton from '../../screenshot-button/index.vue'

const store = useStore()
const [, historyDispatcher] = useHistory()
const call = useCall()
const reset = useReset()

const onClick = () => {
  const { image, width, height, history, bounds } = store
  historyDispatcher.clearSelect()

  setTimeout(() => {
    if (!store.canvasContext || !image || !bounds) {
      return
    }
    composeImage({
      image,
      width,
      height,
      history,
      bounds
    }).then(blob => {
      call.onOk(blob, bounds)
      reset()
    })
  })
}
</script>

<template>
  <ScreenshotButton title="确定" icon='icon-ok' @click="onClick" />
</template>
